api_platform:
    title: "Lorem News API"
    version: "1.0.0"

    formats:
        json: ['application/json']

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    eager_loading:
        force_eager: false

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
