name: Deploy to VPS

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  frontend:
    uses: ./.github/workflows/frontend-main.yml

  #backend:
  #  uses: ./.github/workflows/backend-main.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [frontend]
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: "51.255.171.110"
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /home/deploy/lorem-news
            git fetch origin main --depth 1
            git reset --hard origin/main
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --build
            docker image prune -f
