name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build, Lint, UnitTest, SonarQube
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      # Étape 1 : Récupération du code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Étape 4 : Exécution de ESLint
      - name: Run ESLint
        run: npm run lint

      # Étape 5 : Exécution des tests
      - name: Run Tests
        run: npm run test

      # Étape 6 : Analyse SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
